### PR TITLE
Support custom AddressRange added support JavaResolver

### PR DESCRIPTION
**Pull request by CodeOfDark**

### CODE REVIEW

**Comment by Washi1337** [comment]
I presume you extracted this `IAddressRange` because `end` can be smaller than `start` of an EH in JVM bytecode?

Did you test your new implementation of address ranges with functions implemented in JVM bytecode?

**Comment by CodeOfDark** [comment]
1- exactly.
2- yes.

**Comment by Washi1337** [comment]
I don't see any unit tests in your PR. 

What is the intended behaviour if these kinds of weird ranges are present in the bytecode method body?

**Comment by CodeOfDark** [comment]
I didn’t push any uni tests, lazy to clean the code xD i will soon

**Pull request closed without merging**
